import {Dimensions, StyleSheet} from 'react-native';
import {
  getFontSize,
  scaledHeightValue,
  scaledValue,
} from '../../../../utils/design.utils';
import {colors} from '../../../../../assets/colors';
import {crossIcon} from '../../../../utils/Images';
import {fonts} from '../../../../utils/fonts';
import {Subheading} from 'react-native-paper';

export const styles = StyleSheet.create({
  dashboardMainView: {
    flex: 1,
    backgroundColor: colors.themeColor,
  },
  scrollView: {
    flex: 1,
  },
  yearlySummaryMainView: {
    backgroundColor: colors.themeColor,
    borderRadius: scaledValue(20),
    marginHorizontal: scaledValue(20),
    flexDirection: 'row',
    paddingVertical: scaledValue(20),
    paddingHorizontal: scaledValue(20),
    shadowColor: '##47382714',
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 20,
    justifyContent: 'space-between',
    marginTop: scaledValue(36),
    shadowOffset: {width: -0, height: -0.5},
  },
  statusCardView1: {flexDirection: 'row', alignItems: 'center'},
  statusCardView2: {flexDirection: 'row', alignItems: 'center'},
  statusCardImageView: {
    width: scaledValue(40),
    height: scaledValue(40),
    backgroundColor: colors.jetBlack50,
    borderRadius: scaledValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearlySummaryText: {
    color: '#302F2E',
    fontSize: scaledValue(12),
    lineHeight: scaledHeightValue(14.4),
  },
  solarWalledImage: {width: scaledValue(20), height: scaledValue(20)},
  statusCardSubText: {
    fontSize: scaledValue(23),
    lineHeight: scaledHeightValue(27.6),
    letterSpacing: scaledValue(23 * -0.01),
  },
  headerRight: {
    // paddingRight: scaledValue(20),
  },
  headerLeft: {
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: scaledValue(20),
    height: scaledValue(20),
  },
  greetingText: {
    fontSize: scaledValue(22),
    lineHeight: scaledHeightValue(31.2),
    letterSpacing: scaledValue(26 * -0.01),
    marginLeft: scaledValue(8),

    textTransform: 'capitalize',
  },
  petsText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    marginTop: scaledValue(24),
    letterSpacing: scaledValue(20 * -0.01),

    paddingHorizontal: scaledValue(20),
  },
  petListContainer: {
    marginTop: scaledValue(10),
    flexDirection: 'row',
    paddingHorizontal: scaledValue(20),
  },
  petList: {
    gap: scaledValue(12),
  },
  petItem: {},
  petImage: isSelected => ({
    width: scaledValue(60),
    height: scaledValue(60),
    borderRadius: scaledValue(30),
    borderColor: isSelected ? colors.primaryBlue : colors.jetBlack,
    borderWidth: scaledValue(1),
  }),
  petNameText: {
    fontSize: scaledValue(16),
    lineHeight: scaledHeightValue(19.2),
    marginTop: scaledValue(8),
    letterSpacing: scaledValue(16 * -0.02),
    textAlign: 'center',
  },
  healthyStatus: {
    flexDirection: 'row',
    backgroundColor: '#8AC1B1',
    paddingHorizontal: scaledValue(10),
    height: scaledValue(24),
    alignItems: 'center',
    borderRadius: scaledValue(20),
  },
  riskStatus: {
    flexDirection: 'row',
    backgroundColor: colors.appRed,
    paddingHorizontal: scaledValue(10),
    height: scaledValue(24),
    alignItems: 'center',
    borderRadius: scaledValue(20),
  },
  statusIcon: {
    width: scaledValue(12),
    height: scaledValue(12),
    marginRight: scaledValue(1),
  },
  statusText: {
    fontSize: scaledValue(12),
    lineHeight: scaledHeightValue(14),
    letterSpacing: scaledValue(12 * -0.02),
    color: colors.white,
    marginLeft: scaledValue(1),
    top: scaledValue(1),
  },
  addPetButton: {
    marginLeft: scaledValue(16),
  },
  addPetImage: {
    width: scaledValue(80),
    height: scaledValue(80),
  },
  addPetText: {
    fontSize: scaledValue(16),
    lineHeight: scaledHeightValue(19.2),
    marginTop: scaledValue(6),
    letterSpacing: scaledValue(16 * -0.02),

    textAlign: 'center',
  },

  wellnessSummaryText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    letterSpacing: scaledValue(20 * -0.01),
    marginTop: scaledValue(36),
    paddingHorizontal: scaledValue(20),
    marginBottom: scaledValue(18),
  },

  quickActionsText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    marginTop: scaledValue(36),
    opacity: 0.6,
    paddingHorizontal: scaledValue(20),
  },
  quickActionsWrapper: {
    // justifyContent: 'space-between',
    gap: scaledValue(32),
  },
  quickActionsList: {
    gap: scaledValue(28),
    marginTop: scaledValue(25),
    marginBottom: scaledValue(151),
    paddingHorizontal: scaledValue(20),
    backgroundColor: colors.paletteWhite,
    borderTopLeftRadius: scaledValue(32),
    borderTopRightRadius: scaledValue(32),
    paddingBottom: scaledValue(36),
    shadowColor: '##47382714',
    // shadowOffset: {width: -0, height: -0.5},
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 20,
  },
  quickActionImageView: {
    width: scaledValue(48),
    height: scaledValue(48),
    backgroundColor: colors.jetBlack,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scaledValue(9.6),
  },
  quickActionItem: {
    // backgroundColor: colors.fawn,
    width: scaledValue(90),
    alignItems: 'center',
  },
  quickActionImage: {
    width: scaledValue(28.8),
    height: scaledValue(28.8),
    tintColor: colors.pearlWhite,
  },
  quickActionText: {
    fontSize: getFontSize(15),
    lineHeight: getFontSize(16.8),
    marginTop: scaledValue(8),
    textAlign: 'center',
  },

  quickAcitonTitleText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    letterSpacing: scaledValue(20 * -0.01),

    marginTop: scaledValue(21),
  },

  wellnessSummaryWrapper: {
    justifyContent: 'space-between',
  },
  wellnessSummaryList: {
    gap: scaledValue(16),
    marginTop: scaledValue(12),
    marginBottom: scaledValue(48),
    marginHorizontal: scaledValue(20),
  },

  wellnessSummaryItemView: {
    backgroundColor: colors.paletteWhite,
    width: Dimensions.get('window').width / 2 - scaledValue(30),
    // height: scaledHeightValue(175),
    borderRadius: scaledValue(20),
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: scaledValue(2)},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 8,
    paddingTop: scaledValue(20),
    alignItems: 'center',
  },

  wellnessSummaryTitle: {
    fontSize: scaledValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    textAlign: 'center',
    marginBottom: scaledValue(16),
  },
  syringeBoldImageView: {
    width: scaledValue(40),
    height: scaledValue(40),
    backgroundColor: colors.softGreen,
    // marginVertical: scaledValue(18),
    // marginLeft: scaledValue(20),
    borderRadius: scaledValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  syringeBoldImage: {width: scaledValue(24), height: scaledValue(24)},
  vaccinationStatusMainView: {
    backgroundColor: colors.themeColor,
    borderRadius: scaledValue(20),
    marginHorizontal: scaledValue(20),
    shadowColor: '##47382714',
    // shadowOffset: {width: -0, height: -0.5},
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 20,
    paddingVertical: scaledValue(20),
    paddingHorizontal: scaledValue(20),
    shadowOffset: {width: -0, height: -0.5},
  },
  vaccinationText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(19.8),
    letterSpacing: scaledValue(18 * -0.01),
  },
  vaccinationStatusText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(19.8),
    letterSpacing: scaledValue(18 * -0.01),
  },
  upToDateView: {
    backgroundColor: colors.pearlWhite,
    paddingHorizontal: scaledValue(8),
    paddingVertical: scaledValue(8.5),
    justifyContent: 'center',
    borderRadius: scaledValue(20),
    alignItems: 'center',
    flexDirection: 'row',
    // marginRight: scaledValue(20),
  },
  upToDateText: {
    fontSize: scaledValue(12),
    letterSpacing: scaledValue(12 * -0.02),
  },
  circleCheckImage: {
    width: scaledValue(12),
    height: scaledValue(12),
    marginRight: scaledValue(2),
  },
  dotStyle: {
    width: scaledValue(10),
    height: scaledValue(10),
    borderRadius: scaledValue(20),
    opacity: 0.4,
  },
  activeDotStyle: {
    width: scaledValue(10),
    height: scaledValue(10),
    borderRadius: scaledValue(20),
  },
  headerView: {
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  teamText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),

    letterSpacing: scaledValue(18 * -0.01),
  },
  countText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    color: colors.jetBlack300,
    letterSpacing: scaledValue(18 * -0.01),
  },
  swiperCardStyle: {
    backgroundColor: colors.paletteWhite,
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: scaledValue(2)},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 8,
  },
  statusView: {
    position: 'absolute',
    bottom: scaledValue(0),
    width: scaledValue(118.25),
    alignItems: 'center',
  },
  subTitleText: {
    fontSize: getFontSize(16),
    lineHeight: getFontSize(19.2),
    marginTop: scaledValue(12),
  },
  graphStatusText: {
    fontSize: getFontSize(13),
    lineHeight: getFontSize(15.6),
    color: colors.jetBlack,
  },

  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: scaledValue(24),
  },
  crossIcon: {
    height: scaledValue(22),
    width: scaledValue(22),
  },
  modalInnerContainer: {
    padding: scaledValue(10),
  },
  dogImage: {
    height: scaledValue(99.88),
    width: scaledValue(156),
    marginTop: scaledValue(30),
    alignSelf: 'center',
  },
  modalContentContainer: {
    paddingHorizontal: scaledValue(14),
    marginBottom: scaledValue(20),
    marginTop: scaledValue(8),
  },
  mainHeading: {
    fontSize: scaledValue(23),
    letterSpacing: scaledValue(23 * -0.01),
    textAlign: 'center',
    lineHeight: scaledValue(27.6),
  },
  emergencyText: {
    color: colors.appRed,
  },
  Subheading: {
    fontSize: scaledValue(14),
    lineHeight: scaledValue(14 * 1.2),
    textAlign: 'center',
    color: colors.jetBlack300,
    marginBottom: scaledValue(24),
    marginTop: scaledValue(4),
  },
  modalImg: {
    resizeMode: 'contain',
    height: scaledValue(48),
    width: scaledValue(48),
    marginTop: scaledValue(12),
  },
  modalFlatlistMain: {
    borderRadius: scaledValue(12),
    flexDirection: 'row',
    borderWidth: scaledValue(1),
    borderColor: colors.jetBlack50,
  },
  modalHeading: {
    marginTop: scaledValue(12),
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    letterSpacing: scaledValue(18 * -0.01),
  },
  modalText: {
    fontSize: scaledValue(11),
    lineHeight: scaledValue(13.2),
    marginBottom: scaledValue(12),
    marginTop: scaledValue(4),
    color: colors.jetBlack300,
  },
  imgView: {
    alignItems: 'center',
    paddingHorizontal: scaledValue(12),
  },
  imageView: {
    // width: '15%',
    // alignItems: 'flex-end',
  },
  searchTouchable: {
    borderWidth: scaledValue(0.5),
    borderColor: colors.jetBlack,
    borderRadius: scaledValue(24),
    paddingVertical: scaledValue(14),
    paddingHorizontal: scaledValue(20),
    marginHorizontal: scaledValue(20),
    marginTop: scaledValue(24),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  searchText: {
    fontSize: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.03),
    opacity: 0.6,
  },
  welcomeTitle: {
    textAlign: 'center',
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),

    lineHeight: scaledHeightValue(20 * 1.2),
    marginTop: scaledValue(24),
  },
  welcomeSubtitle: {
    textAlign: 'center',
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),
    color: colors.appRed,
    lineHeight: scaledHeightValue(20 * 1.2),
  },

  welcomeImage: {
    width: Dimensions.get('window').width,
    height: scaledValue(250),
    marginTop: scaledValue(4),
  },
  addCompanionTouchable: {
    width: scaledValue(159),
    backgroundColor: colors.primaryBlue,
    borderRadius: scaledValue(20),
    marginHorizontal: scaledValue(19),
    marginTop: scaledValue(12),
  },
  addCompanionImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  solarCircleImage: {
    width: scaledValue(32),
    height: scaledValue(32),
    left: scaledValue(15),
    top: scaledValue(20),
  },

  pawImage: {
    width: scaledValue(113.18),
    height: scaledValue(113.18),
    left: scaledValue(20),
  },
  addCompanionText: {
    color: colors.pearlWhite,
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(18 * 1.2),
    letterSpacing: scaledValue(18 * -0.01),
    bottom: scaledValue(15),
    textAlign: 'center',
  },
  upcomingHeading: {
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),
    lineHeight: scaledHeightValue(20 * 1.2),
    marginHorizontal: scaledValue(20),
    marginTop: scaledValue(21),
  },
  noUpcomingContainer: {
    width: Dimensions.get('window').width - 40,
    backgroundColor: colors.paletteWhite,
    alignSelf: 'center',
    paddingVertical: scaledValue(20),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scaledValue(20),
    marginTop: scaledValue(12),
    shadowColor: '##47382714',
    shadowOffset: {width: 10, height: 10},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  noUpcomingText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(18 * 1.2),
    letterSpacing: scaledValue(18 * -0.01),
    textAlign: 'center',
    color: colors.jetBlack,
  },
  noUpcomingSubText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(14 * 1.4),
    marginTop: scaledValue(4),
    textAlign: 'center',
    color: colors.jetBlack,
  },
  assessmentHeading: {
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),
    lineHeight: scaledHeightValue(20 * 1.2),
    marginHorizontal: scaledValue(20),
    marginTop: scaledValue(24),
  },
  noAssessmentContainer: {
    width: Dimensions.get('window').width - 40,
    backgroundColor: colors.paletteWhite,
    alignSelf: 'center',
    paddingVertical: scaledValue(20),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scaledValue(20),
    marginTop: scaledValue(12),
    marginBottom: scaledValue(22),
    shadowColor: '##47382714',
    shadowOffset: {width: 10, height: 10},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  noAssessmentText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(18 * 1.2),
    letterSpacing: scaledValue(18 * -0.01),
    textAlign: 'center',
    color: colors.jetBlack,
  },
  noAssessmentSubText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(14 * 1.4),
    marginTop: scaledValue(4),
    textAlign: 'center',
    color: colors.jetBlack,
    paddingHorizontal: scaledValue(60),
  },
  swiperPaginationStyle: {
    bottom: 0,
    marginBottom: 0,
  },

  editIconImage: {
    height: scaledValue(20),
    width: scaledValue(20),
  },
  modalListContent: {
    gap: scaledValue(12),
  },
  headerContainerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: scaledValue(20),
  },
  emergencyIcon: {
    width: scaledValue(20),
    height: scaledValue(20),
    marginRight: scaledValue(12),
  },
  headerContainerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: scaledValue(20),
  },
  userImage: {
    width: scaledValue(40),
    height: scaledValue(40),
    borderRadius: scaledValue(40),
    borderWidth: scaledValue(1),
    borderColor: colors.primaryBlue,
  },
  greetingText: {
    marginLeft: scaledValue(8), // Optional spacing
  },
  petItemContainer: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  petImageBorder: isSelected => ({
    borderRadius: scaledValue(30),
    borderWidth: scaledValue(1),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: isSelected ? colors.primaryBlue : colors.jetBlack,
  }),
  petUnderline: isSelected => ({
    width: scaledValue(80),
    height: scaledValue(1),
    backgroundColor: isSelected ? '#247AED' : 'transparent',
    marginTop: scaledValue(5),
  }),
  petNameText: {
    marginTop: scaledValue(6),
  },
});
