import {Dimensions, StyleSheet} from 'react-native';
import {
  getFontSize,
  scaledHeightValue,
  scaledValue,
} from '../../../../utils/design.utils';
import {colors} from '../../../../../assets/colors';
import {crossIcon} from '../../../../utils/Images';
import {fonts} from '../../../../utils/fonts';
import {Subheading} from 'react-native-paper';

export const styles = StyleSheet.create({
  dashboardMainView: {
    flex: 1,
    backgroundColor: colors.themeColor,
  },
  scrollView: {
    flex: 1,
  },
  yearlySummaryMainView: {
    backgroundColor: colors.fawn,
    borderRadius: scaledValue(20),
    marginTop: scaledValue(28),
    marginBottom: scaledValue(28),
    marginHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusCardView1: {flexDirection: 'row', alignItems: 'center'},
  statusCardView2: {flexDirection: 'row', alignItems: 'center', width: '85%'},
  statusCardImageView: {
    width: scaledValue(40),
    height: scaledValue(40),
    backgroundColor: '#FFEDD9',
    marginVertical: scaledValue(18),
    marginLeft: scaledValue(20),
    borderRadius: scaledValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearlySummaryText: {
    color: '#302F2E',
    fontSize: scaledValue(12),
    lineHeight: scaledHeightValue(14.4),
  },
  solarWalledImage: {width: scaledValue(20), height: scaledValue(20)},
  statusCardSubText: {
    color: colors.darkPurple,
    fontSize: scaledValue(23),
    lineHeight: scaledHeightValue(27.6),
    letterSpacing: scaledValue(23 * -0.01),
  },
  headerRight: {
    // paddingRight: scaledValue(20),
  },
  headerLeft: {
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: scaledValue(28),
    height: scaledValue(28),
  },
  greetingText: {
    fontSize: scaledValue(22),
    lineHeight: scaledHeightValue(31.2),
    letterSpacing: scaledValue(26 * -0.01),
    marginLeft: scaledValue(8),
    color: colors.darkPurple,
    textTransform: 'capitalize',
  },
  petsText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    marginTop: scaledValue(40),
    letterSpacing: scaledValue(20 * -0.01),
    color: colors.darkPurple,
    paddingHorizontal: scaledValue(20),
  },
  petListContainer: {
    marginTop: scaledValue(10),
    flexDirection: 'row',
    paddingHorizontal: scaledValue(20),
  },
  petList: {
    gap: scaledValue(12),
  },
  petItem: {},
  petImage: {
    width: scaledValue(80),
    height: scaledValue(80),
  },
  petNameText: {
    fontSize: scaledValue(16),
    lineHeight: scaledHeightValue(19.2),
    marginTop: scaledValue(4),
    letterSpacing: scaledValue(16 * -0.02),
    color: colors.darkPurple,
    textAlign: 'center',
  },
  healthyStatus: {
    flexDirection: 'row',
    backgroundColor: '#8AC1B1',
    paddingHorizontal: scaledValue(10),
    height: scaledValue(24),
    alignItems: 'center',
    borderRadius: scaledValue(20),
  },
  riskStatus: {
    flexDirection: 'row',
    backgroundColor: colors.appRed,
    paddingHorizontal: scaledValue(10),
    height: scaledValue(24),
    alignItems: 'center',
    borderRadius: scaledValue(20),
  },
  statusIcon: {
    width: scaledValue(12),
    height: scaledValue(12),
    marginRight: scaledValue(1),
  },
  statusText: {
    fontSize: scaledValue(12),
    lineHeight: scaledHeightValue(14),
    letterSpacing: scaledValue(12 * -0.02),
    color: colors.white,
    marginLeft: scaledValue(1),
    top: scaledValue(1),
  },
  addPetButton: {
    marginLeft: scaledValue(16),
  },
  addPetImage: {
    width: scaledValue(80),
    height: scaledValue(80),
  },
  addPetText: {
    fontSize: scaledValue(16),
    lineHeight: scaledHeightValue(19.2),
    marginTop: scaledValue(6),
    letterSpacing: scaledValue(16 * -0.02),
    color: colors.darkPurple,
    textAlign: 'center',
  },

  wellnessSummaryText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    letterSpacing: scaledValue(20 * -0.01),
    marginTop: scaledValue(36),
    paddingHorizontal: scaledValue(20),
    marginBottom: scaledValue(18),
  },

  quickActionsText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    marginTop: scaledValue(36),
    opacity: 0.6,
    paddingHorizontal: scaledValue(20),
  },
  quickActionsWrapper: {
    // justifyContent: 'space-between',
    gap: scaledValue(32),
  },
  quickActionsList: {
    gap: scaledValue(28),
    paddingTop: scaledValue(32),
    marginBottom: scaledValue(151),
    paddingHorizontal: scaledValue(20),
    backgroundColor: colors.pearlWhite,
    borderTopLeftRadius: scaledValue(32),
    borderTopRightRadius: scaledValue(32),
    paddingBottom: scaledValue(36),
  },
  quickActionImageView: {
    width: scaledValue(48),
    height: scaledValue(48),
    backgroundColor: colors.appRed,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scaledValue(9.6),
  },
  quickActionItem: {
    // backgroundColor: colors.fawn,
    width: scaledValue(90),
    alignItems: 'center',
  },
  quickActionImage: {
    width: scaledValue(28.8),
    height: scaledValue(28.8),
    tintColor: colors.pearlWhite,
  },
  quickActionText: {
    fontSize: getFontSize(15),
    lineHeight: getFontSize(16.8),
    marginTop: scaledValue(8),
    textAlign: 'center',
    color: colors.darkPurple,
  },

  quickAcitonTitleText: {
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    letterSpacing: scaledValue(20 * -0.01),
    color: colors.darkPurple,
  },

  wellnessSummaryWrapper: {
    justifyContent: 'space-between',
  },
  wellnessSummaryList: {
    gap: scaledValue(16),
    marginTop: scaledValue(12),
    marginBottom: scaledValue(48),
    marginHorizontal: scaledValue(20),
  },

  wellnessSummaryItemView: {
    backgroundColor: '#FFF6EB',
    width: Dimensions.get('window').width / 2 - scaledValue(30),
    // height: scaledHeightValue(175),
    borderRadius: scaledValue(20),
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: scaledValue(2)},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 8,
    paddingTop: scaledValue(20),
    alignItems: 'center',
  },

  wellnessSummaryTitle: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    marginBottom: scaledValue(16),
    letterSpacing: scaledValue(18 * -0.01),
    textAlign: 'center',
  },
  syringeBoldImageView: {
    width: scaledValue(40),
    height: scaledValue(40),
    backgroundColor: colors.softGreen,
    marginVertical: scaledValue(18),
    marginLeft: scaledValue(20),
    borderRadius: scaledValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  syringeBoldImage: {width: scaledValue(24), height: scaledValue(24)},
  vaccinationStatusMainView: {
    backgroundColor: colors.cambridgeBlue,
    borderRadius: scaledValue(20),
    marginHorizontal: scaledValue(20),
    marginBottom: scaledValue(36),
  },
  vaccinationText: {
    color: colors.pearlWhite,
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(19.8),
    letterSpacing: scaledValue(18 * -0.01),
  },
  vaccinationStatusText: {
    color: colors.pearlWhite,
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(19.8),
    letterSpacing: scaledValue(18 * -0.01),
  },
  upToDateView: {
    backgroundColor: colors.pearlWhite,
    paddingHorizontal: scaledValue(8),
    paddingVertical: scaledValue(8.5),
    justifyContent: 'center',
    borderRadius: scaledValue(20),
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: scaledValue(20),
  },
  upToDateText: {
    fontSize: scaledValue(12),
    letterSpacing: scaledValue(12 * -0.02),
  },
  circleCheckImage: {
    width: scaledValue(12),
    height: scaledValue(12),
    marginRight: scaledValue(2),
  },
  dotStyle: {
    width: scaledValue(10),
    height: scaledValue(10),
    borderRadius: scaledValue(20),
    opacity: 0.4,
  },
  activeDotStyle: {
    width: scaledValue(10),
    height: scaledValue(10),
    borderRadius: scaledValue(20),
  },
  headerView: {
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  teamText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    color: colors.darkPurple,
    letterSpacing: scaledValue(18 * -0.01),
  },
  countText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    color: colors.appRed,
    letterSpacing: scaledValue(18 * -0.01),
  },
  swiperCardStyle: {
    backgroundColor: colors.offWhite,
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: scaledValue(2)},
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 8,
  },
  statusView: {
    position: 'absolute',
    bottom: scaledValue(42),
    width: scaledValue(118.25),
    alignItems: 'center',
  },
  subTitleText: {
    fontSize: getFontSize(16),
    lineHeight: getFontSize(19.2),
    color: colors.jetBlack,
    // paddingTop:20
    marginTop: scaledValue(12),
  },
  graphStatusText: {
    fontSize: getFontSize(13),
    lineHeight: getFontSize(15.6),
    color: colors.jetBlack,
  },

  modalContainer: {
    backgroundColor: colors.white,
    // height: scaledValue(620.13),
    borderRadius: scaledValue(24),
    // paddingVertical: scaledValue(30),
    // paddingHorizontal:scaledValue(20),
  },
  crossIcon: {
    height: scaledValue(22),
    width: scaledValue(22),
    alignSelf: 'flex-end',
    position: 'absolute',
    top: scaledValue(10),
    right: scaledValue(10),
  },
  modalInnerContainer: {
    padding: scaledValue(10),
  },
  dogImage: {
    height: scaledHeightValue(165.23),
    width: '100%',
    marginTop: scaledValue(20),
    resizeMode: 'contain',
  },
  modalContentContainer: {
    paddingHorizontal: scaledValue(14),
    marginBottom: scaledValue(20),
    marginTop: scaledValue(12),
  },
  mainHeading: {
    fontSize: scaledValue(23),
    letterSpacing: scaledValue(23 * -0.01),
    textAlign: 'center',
    lineHeight: scaledValue(27.6),
    color: colors.black,
    fontFamily: fonts.CLASH_GRO_MEDIUM,
  },
  emergencyText: {
    color: colors.appRed,
  },
  Subheading: {
    fontSize: scaledValue(14),
    lineHeight: scaledValue(16.8),
    fontFamily: fonts.SATOSHI_REGULAR,
    textAlign: 'center',
    color: '#595958',
    marginBottom: scaledValue(24),
    marginTop: scaledValue(4),
  },
  modalImg: {
    resizeMode: 'contain',
    height: scaledValue(48),
    width: scaledValue(48),
    marginTop: scaledValue(12),
  },
  modalFlatlistMain: {
    borderRadius: scaledValue(12),
    flexDirection: 'row',
    borderWidth: scaledValue(1),
    borderColor: '#BFBFBE',
  },
  modalHeading: {
    marginTop: scaledValue(12),
    fontSize: scaledValue(18),
    fontFamily: fonts.CLASH_GRO_MEDIUM,
    lineHeight: scaledHeightValue(21.6),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.black,
  },
  modalText: {
    fontSize: scaledValue(11),
    lineHeight: scaledValue(13.2),
    fontFamily: fonts.SATOSHI_MEDIUM,
    marginBottom: scaledValue(12),
    marginTop: scaledValue(4),
  },
  imgView: {
    alignItems: 'center',
    paddingHorizontal: scaledValue(12),
  },
  imageView: {
    width: '15%',
    alignItems: 'flex-end',
  },
});
