import type { Metadata } from "next";
import "./globals.css";

// react bootstrap 
import 'bootstrap/dist/css/bootstrap.min.css';

// Slick Slider 
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { AuthProvider } from "./Context/AuthContext";


export const metadata: Metadata = {
  title: "Yosemite Crew",
  description: "Generated by Yosemite Crew",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
         <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
