import type { Metadata } from "next";
import "./globals.css";

import "bootstrap/dist/css/bootstrap.min.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SessionInitializer from "./components/SessionInitializer";

export const metadata: Metadata = {
  title: "Yosemite Crew",
  description: "Generated by Yosemite Crew",
  icons: [
    { rel: "icon", url: "/favicon.ico", type: "image/x-icon" },
    {
      rel: "icon",
      url: "/favicon-32x32.png",
      sizes: "32x32",
      type: "image/png",
    },
    {
      rel: "icon",
      url: "/favicon-16x16.png",
      sizes: "16x16",
      type: "image/png",
    },
    { rel: "apple-touch-icon", url: "/apple-touch-icon.png", sizes: "180x180" },
  ],
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionInitializer>{children}</SessionInitializer>
      </body>
    </html>
  );
}
