import {Dimensions, StyleSheet} from 'react-native';
import {colors} from '../../../../../../assets/colors';
import {scaledValue} from '../../../../../utils/design.utils';
import {fonts} from '../../../../../utils/fonts';
const deviceW = Dimensions.get('window').width;
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.themeColor,
  },
  yearlySpendView: {
    marginHorizontal: scaledValue(20),
    borderRadius: scaledValue(20),
    marginTop: scaledValue(22),
    justifyContent: 'center',
    alignItems: 'center',
  },

  subHeading: {
    fontSize: scaledValue(18),
    lineHeight: scaledValue(21.6),
    letterSpacing: scaledValue(18 * -0.01),
    marginTop: scaledValue(8),
    color: colors.paletteWhite,
    marginBottom: scaledValue(8),
  },
  price: {
    fontSize: scaledValue(23),
    lineHeight: scaledValue(27.6),
    letterSpacing: scaledValue(23 * -0.01),
    color: colors.paletteWhite,
    marginBottom: scaledValue(26),
  },
  addImage: {
    height: scaledValue(20),
    width: scaledValue(20),
  },
  recentText: {
    fontSize: scaledValue(26),
    letterSpacing: scaledValue(26 * -0.01),
  },
  recentView: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginTop: scaledValue(24),
    width: '100%',
    paddingHorizontal: scaledValue(20),
  },
  flatlistMain: {
    width: deviceW - scaledValue(40),
    justifyContent: 'space-between',
    paddingVertical: scaledValue(16),
    backgroundColor: colors.white,
    borderWidth: scaledValue(1),
    borderColor: colors.paletteWhite,
    shadowColor: '##47382714',
    shadowOffset: {width: -0, height: -0.5},
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 20,
    borderRadius: scaledValue(24),
    alignSelf: 'center',
  },
  threeDots: {
    height: scaledValue(16),
    width: scaledValue(16),
  },
  priceText: {
    fontSize: scaledValue(18),
    lineHeight: scaledValue(18 * 1.2),
    letterSpacing: scaledValue(18 * -0.01),
    textAlign: 'center',
  },
  statusText: {
    fontSize: scaledValue(15),
    lineHeight: scaledValue(15 * 1.2),
    letterSpacing: scaledValue(15 * -0.02),
    color: colors.platteSuccess,
    textAlign: 'center',
  },
  priceView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskText: {
    fontSize: scaledValue(23),
    letterSpacing: scaledValue(23 * -0.01),
  },
  dateText: {
    color: colors.jetBlack300,
    fontSize: scaledValue(11),
    marginTop: scaledValue(7),
    textAlign: 'center',
  },
  modalContainer: {
    backgroundColor: colors.themeColor,
    // height: scaledValue(557),
    borderRadius: scaledValue(24),
    paddingHorizontal: scaledValue(24),
    alignItems: 'center',
  },
  crossIcon: {
    height: scaledValue(22),
    width: scaledValue(22),
  },
  kiziImage: {
    height: scaledValue(63),
    width: scaledValue(63),
    borderRadius: scaledValue(31.5),
  },
  addText: {
    letterSpacing: scaledValue(26 * -0.06),
    fontSize: scaledValue(26),
    marginTop: scaledValue(8),
  },

  input: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingLeft: scaledValue(10),
    marginTop: scaledValue(40),
  },
  inputAmount: {
    width: '100%',
    marginTop: scaledValue(12),
    marginBottom: scaledValue(48),
  },
  iconStyle: {
    height: scaledValue(20),
    width: scaledValue(20),
  },
  iconLeftStyle: {
    height: scaledValue(20),
    width: scaledValue(20),
  },
  categoryText: {
    fontSize: scaledValue(16),
    lineHeight: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.03),
    fontFamily: fonts.SATOSHI_REGULAR,
    color: '#000000',
    opacity: 0.8,
  },
  categoryView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    borderWidth: scaledValue(0.5),
    width: '100%',
    borderRadius: scaledValue(24),
    color: '#312943',
    paddingHorizontal: scaledValue(20),
    height: scaledValue(48),
    marginTop: scaledValue(16),
  },
  expenseDateText: {
    fontSize: scaledValue(16),
    lineHeight: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.03),
    fontFamily: fonts.SATOSHI_REGULAR,
    color: '#000000',
    opacity: 0.8,
  },
  calendarView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',

    alignSelf: 'center',
    borderWidth: scaledValue(0.5),
    width: '100%',
    borderRadius: scaledValue(24),
    color: '#312943',
    paddingHorizontal: scaledValue(20),
    height: scaledValue(48),
    marginTop: scaledValue(16),
  },
  buttonStyle: {
    borderRadius: scaledValue(28),
    gap: scaledValue(6),
    marginBottom: scaledValue(48),
    width: '100%',
  },
  buttonIcon: {
    height: scaledValue(20),
    width: scaledValue(20),
    marginRight: scaledValue(8),
  },
  petView: {
    borderWidth: scaledValue(1),
    marginTop: scaledValue(26),
    borderRadius: scaledValue(32),
    borderColor: colors.primaryBlue,
  },
  billText: {
    fontSize: scaledValue(14),
    marginTop: scaledValue(8),
  },
  businessText: {
    fontSize: scaledValue(15),
    marginTop: scaledValue(8),
    letterSpacing: scaledValue(15 * -0.02),
    color: colors.jetBlack300,
    width: Dimensions.get('window').width - scaledValue(40 + 36 + 80 + 36),
  },
  optionsWrapper: {
    paddingVertical: scaledValue(20),
    alignSelf: 'center',
  },
  optionsContainer: {
    borderRadius: scaledValue(24),
    marginTop: scaledValue(25),
    width: 'auto',
    paddingHorizontal: scaledValue(19),
  },
  editImg: {
    width: scaledValue(14),
    height: scaledValue(14),
  },
  menuOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaledValue(4),
    borderWidth: scaledValue(1),
    borderColor: colors.jetBlack,
    paddingVertical: scaledValue(12),
    borderRadius: scaledValue(28),
    paddingHorizontal: scaledValue(19),
  },
  menuDivider: {
    borderWidth: scaledValue(1),
    width: scaledValue(136),
    borderColor: '#EAEAEA',
    marginVertical: scaledValue(8),
  },
  dotView: {
    width: scaledValue(55),
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuView: {alignSelf: 'flex-end'},
  tileContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: scaledValue(4),
    paddingHorizontal: scaledValue(18),
  },
  innerTileContainer: {
    width: Dimensions.get('window').width - scaledValue(40 + 36 + 80 + 16),
  },
  priceTile: val => ({
    backgroundColor: val === 'Paid' ? '#E6F4EF' : '#FEF3E9',
    borderRadius: scaledValue(8),
    justifyContent: 'center',
    alignItems: 'center',
    gap: scaledValue(4),
    minWidth: scaledValue(80),
    maxWidth: scaledValue(80),
    minHeight: scaledValue(77),
    maxHeight: scaledValue(77),
  }),
  payBtnView: {
    backgroundColor: 'transparent',
    borderWidth: scaledValue(1),
    marginTop: scaledValue(16),
    height: scaledValue(44),
    gap: scaledValue(6),
    marginHorizontal: scaledValue(16),
  },
  payTxtStyle: {
    color: colors.jetBlack,
    fontSize: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.01),
  },
  expenseBtn: {
    gap: scaledValue(8),
    marginTop: scaledValue(24),
    marginHorizontal: scaledValue(20),
  },
  outstandAmt: {
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),
    textAlign: 'right',
  },
  outstandTxt: {
    fontSize: scaledValue(14),
    color: colors.errorRed,
  },
  flatListContainer: {
    marginTop: scaledValue(24),
    gap: scaledValue(12),
    marginBottom: scaledValue(28),
  },
  crossIconStyle: {
    alignSelf: 'flex-end',
    position: 'absolute',
    top: scaledValue(19.5),
    right: scaledValue(20),
  },
  crossIconView: {
    alignSelf: 'flex-end',
    position: 'absolute',
    top: scaledValue(19.5),
    right: scaledValue(20),
  },
  scanText: {
    fontSize: scaledValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    marginTop: scaledValue(10),
  },
});
