import {StyleSheet} from 'react-native';
import {
  scaledHeightValue,
  scaledValue,
} from '../../../../../utils/design.utils';
import {fonts} from '../../../../../utils/fonts';
import {colors} from '../../../../../../assets/colors';

export const styles = StyleSheet.create({
  dashboardMainView: {
    flex: 1,
    backgroundColor: colors.themeColor,
  },
  doctorNameText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.8),
    letterSpacing: scaledValue(18 * -0.01),
    color: '#090A0A',
  },
  doctorImgStyle: {
    width: scaledValue(88),
    height: scaledValue(88),
    borderRadius: scaledValue(12),
  },
  card: {
    width: scaledValue(335),
    backgroundColor: '#FEF8F4',
    flexDirection: 'row',
    marginTop: scaledValue(22),
    marginHorizontal: scaledValue(20),
    borderRadius: scaledValue(20),
    paddingBottom: scaledValue(16),
    paddingTop: scaledValue(12),
    paddingLeft: scaledValue(12),
  },
  departmentText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    color: colors.darkPurple,
    opacity: 0.7,
    marginTop: scaledValue(2),
  },
  textView: {
    marginLeft: scaledValue(8),
  },
  ongoingText: {
    fontSize: scaledValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.appRed,
  },
  plansText: {
    fontSize: scaledValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.darkPurple,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scaledValue(28),
    paddingHorizontal: scaledValue(19),
  },
  petTitle: {
    fontSize: scaledValue(16),
    lineHeight: scaledHeightValue(19.2),
    letterSpacing: scaledValue(16 * -0.02),
    color: colors.darkPurple,
    marginTop: scaledValue(4),
  },
  imgStyle: {
    width: scaledValue(60),
    height: scaledValue(60),
  },
  petItem: {
    alignItems: 'center',
  },
  petListContainer: {
    flexDirection: 'row',
    marginTop: scaledValue(16),
    gap: scaledValue(12),
    paddingHorizontal: scaledValue(19),
  },
  professionalButton: {
    borderWidth: scaledValue(0.5),
    height: scaledValue(48),
    marginTop: scaledValue(12),
    borderRadius: scaledValue(24),
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: scaledValue(20),
  },
  professionalText: {
    fontSize: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.03),
    color: colors.darkPurple2,
  },
  arrowIcon: {
    width: scaledValue(20),
    height: scaledValue(20),
  },
  dayText: (pickSlot, item) => ({
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    color: pickSlot === item ? colors.paletteWhite : colors.jetBlack,
    opacity: 0.7,
    marginTop: scaledValue(8),
  }),
  dateText: (pickSlot, item) => ({
    fontSize: scaledValue(20),
    lineHeight: scaledHeightValue(24),
    color: pickSlot === item ? colors.paletteWhite : colors.jetBlack,
    letterSpacing: scaledValue(20 * -0.01),
  }),
  slotText: (pickSlot, item) => ({
    fontSize: scaledValue(13),
    lineHeight: scaledHeightValue(15.6),
    color: pickSlot === item ? colors.paletteWhite : colors.appRed,
    marginTop: scaledValue(8),
    marginBottom: scaledValue(8),
  }),
  slotTime: (pickSlotTime, item) => ({
    fontSize: scaledValue(13),
    lineHeight: scaledHeightValue(15.6),
    color: pickSlotTime === item?.slot?.time ? colors.white : colors.jetBlack,
    textAlign: 'center',
    opacity: item?.booked ? 0.4 : 1,
  }),
  inputStyle: {
    height: scaledValue(114),
    marginTop: scaledValue(12),
    borderRadius: scaledValue(100),
    borderColor: '#312943',
    backgroundColor: 'transparent',
    width: '100%',
    // textAlignVertical: 'top',
  },
  uploadContainer: {
    width: scaledValue(335),
    borderWidth: scaledValue(1),
    borderStyle: 'dashed',
    borderRadius: scaledValue(20),
    borderColor: '#37223C4D',
    marginTop: scaledValue(32),
    alignSelf: 'center',
  },
  uploadImage: {
    width: scaledValue(40),
    height: scaledValue(40),
    alignSelf: 'center',
    marginTop: scaledValue(16),
  },
  uploadText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(21.6),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.darkPurple,
    textAlign: 'center',
    paddingHorizontal: scaledValue(53),
    marginTop: scaledValue(10),
  },
  documentText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    color: colors.darkPurple,
    textAlign: 'center',
    paddingHorizontal: scaledValue(53),
    opacity: 0.7,
    marginTop: scaledValue(10),
    marginBottom: scaledValue(16),
  },
  buttonText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.brown,
    fontFamily: fonts?.CLASH_GRO_MEDIUM,
  },
  buttonStyle: {
    backgroundColor: '#FDBD74',
    marginTop: scaledValue(40),
    marginBottom: scaledValue(62),
    height: scaledValue(52),
    borderRadius: scaledValue(28),
    marginHorizontal: scaledValue(20),
  },
  slotListUpperView: {
    marginTop: scaledValue(28),
    marginLeft: scaledValue(20),
  },
  slotCard: (pickSlot, item) => ({
    backgroundColor: pickSlot === item?.date ? colors.appRed : '#FFF6EB',
    width: scaledValue(64),
    borderRadius: scaledValue(8),
    alignItems: 'center',
    opacity: item?.availableSlotsCount === 0 && 0.5,
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  }),
  slotTimeUpperView: {
    marginTop: scaledValue(39),
    paddingHorizontal: scaledValue(20),
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: scaledValue(8),
    rowGap: scaledValue(16),
  },
  slotTimeCard: (pickSlotTime, i) => ({
    backgroundColor:
      pickSlotTime === i?.slot?.time ? colors.appRed : 'transparent',
    borderRadius: scaledValue(8),
    height: scaledValue(40),
    justifyContent: 'center',
    shadowColor: '#47382726',
    shadowOffset: {width: 1, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
    borderWidth: i?.booked
      ? scaledValue(0.5)
      : pickSlotTime != i?.slot?.time
      ? scaledValue(0.75)
      : 0,
    paddingHorizontal: scaledValue(11),
    opacity: i?.booked && 0.4,
    borderColor: colors.jetBlack,
  }),
  timeContentContainer: {
    gap: scaledValue(8),
    backgroundColor: 'red',
    // marginBottom: scaledHeightValue(16),
    // paddingHorizontal: scaledValue(20),
  },
  input: {
    width: '100%',
    backgroundColor: 'transparent',
    fontSize: scaledValue(16),
    // lineHeight: scaledValue(16),
    // marginTop: scaledValue(20),
    paddingLeft: scaledValue(10),
  },
});
