import {Dimensions, StyleSheet} from 'react-native';
import {
  scaledHeightValue,
  scaledValue,
} from '../../../../../utils/design.utils';
import {fonts} from '../../../../../utils/fonts';
import {colors} from '../../../../../../assets/colors';

export const styles = StyleSheet.create({
  dashboardMainView: {
    flex: 1,
    backgroundColor: colors.themeColor,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: scaledValue(18),
    paddingHorizontal: scaledValue(16),
    marginHorizontal: scaledValue(16),
    borderWidth: scaledValue(0.75),
    borderColor: colors.darkPurple,
    height: scaledValue(48),
    borderRadius: scaledValue(28),
  },
  searchBarText: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    opacity: 0.7,
  },
  searchBarIcon: {
    width: scaledValue(24),
    height: scaledValue(24),
  },
  fileListContainer: {
    paddingHorizontal: scaledValue(10),
  },
  fileListContentContainer: {
    gap: scaledValue(16),
    marginBottom: 10,
    backgroundColor: colors.paletteWhite,
  },
  fileItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.paletteWhite,
    borderRadius: scaledValue(20),
    shadowColor: '##47382714',
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 20,
    shadowOffset: {width: -0, height: -0.5},
    marginHorizontal: scaledValue(10),
    paddingVertical: scaledValue(16),
  },
  fileItemImage: {
    width: scaledValue(40),
    height: scaledValue(40),
    tintColor: colors.jetBlack,
    borderRadius: scaledValue(8),
  },
  fileItemTextContainer: {
    marginLeft: scaledValue(13),
  },
  fileItemTitle: {
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(20 * -0.01),
    textTransform: 'capitalize',
  },
  fileItemSubtitle: {
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16.8),
    opacity: 0.5,
  },
  button: {
    height: scaledValue(48),
    width: scaledValue(198),
    alignSelf: 'center',
    marginTop: scaledValue(40),
    backgroundColor: colors.jetBlack,
    borderRadius: scaledValue(28),
    marginBottom: scaledValue(60),
  },
  buttonText: {
    fontSize: scaledValue(18),
    lineHeight: scaledHeightValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    fontFamily: fonts?.CLASH_GRO_MEDIUM,
    color: colors.white,
    marginLeft: scaledValue(3),
    top: scaledValue(2),
  },
  buttonIcon: {
    width: scaledValue(20),
    height: scaledValue(20),
    marginRight: scaledValue(3),
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: scaledValue(20),
    marginTop: scaledValue(20),
    gap: scaledValue(9),
    marginBottom: scaledValue(16),
  },
  tabText: {
    textAlign: 'center',
    color: colors.richBlack,
    fontSize: scaledValue(20),
    letterSpacing: scaledValue(-0.2),
  },
  tabUnderline: {
    borderWidth: scaledValue(1),
    borderColor: colors.primaryBlue,
    marginTop: scaledValue(3),
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: scaledValue(50),
    paddingHorizontal: scaledValue(30),
  },
  emptyImage: {
    width: scaledValue(220),
    height: scaledValue(235),
    resizeMode: 'contain',
  },
  emptyTitle: {
    textAlign: 'center',
    fontSize: scaledValue(20),
    marginTop: scaledValue(16),
    letterSpacing: scaledValue(-0.2),
  },
  emptySubtitle: {
    textAlign: 'center',
    fontSize: scaledValue(14),
    lineHeight: scaledHeightValue(16),
    marginTop: scaledValue(10),
  },
  dotView: {
    width: scaledValue(50),
    height: scaledValue(25),
    alignItems: 'center',
  },
  threeDot: {width: scaledValue(20), height: scaledValue(20)},
  editImg: {
    width: scaledValue(14),
    height: scaledValue(14),
    tintColor: colors.jetBlack,
  },
  optionsContainer: {
    borderRadius: scaledValue(24),
    marginTop: scaledValue(25),
    width: 'auto',
    paddingHorizontal: scaledValue(19),
  },
  optionsWrapper: {
    paddingVertical: scaledValue(20),
    alignSelf: 'center',
  },
  menuOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaledValue(4),
    borderWidth: scaledValue(1),
    borderColor: colors.jetBlack,
    paddingVertical: scaledValue(12),
    borderRadius: scaledValue(28),
    paddingHorizontal: scaledValue(15),
    justifyContent: 'center',
  },
  menuDivider: {
    borderWidth: scaledValue(1),
    width: scaledValue(153),
    borderColor: '#EAEAEA',
    marginVertical: scaledValue(8),
  },
  editText: {
    fontSize: scaledValue(14),
    letterSpacing: scaledValue(14 * -0.01),
    textAlign: 'center',
  },
  recordItemContainer: {
    borderWidth: scaledValue(1),
    borderRadius: scaledValue(20),
    marginHorizontal: scaledValue(10),
    paddingHorizontal: scaledValue(12),
    paddingVertical: scaledValue(15),
    borderColor: colors.jetBlack50,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  recordHeader: {
    flexDirection: 'row',
  },
  doctorImage: {
    width: scaledValue(88),
    height: scaledValue(88),
    borderRadius: scaledValue(12),
  },
  recordTextSection: {
    marginLeft: scaledValue(8),
    width: '60%',
  },
  doctorName: {
    fontSize: scaledValue(18),
    color: colors.richBlack,
    letterSpacing: scaledValue(18 * -0.01),
  },
  subText: {
    fontSize: scaledValue(14),
    opacity: 0.7,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.jetBlack50,
    marginTop: scaledValue(12),
    paddingVertical: scaledValue(16),
    borderRadius: scaledValue(12),
    justifyContent: 'center',
    gap: scaledValue(6),
    marginBottom: scaledValue(17),
  },
  dateIcon: {
    width: scaledValue(16),
    height: scaledValue(16),
  },
  dateText: {
    fontSize: scaledValue(16),
    letterSpacing: scaledValue(16 * -0.01),
  },
  recordFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: scaledValue(12),
  },
  recordName: {
    fontSize: scaledValue(18),
    letterSpacing: scaledValue(18 * -0.01),
    color: colors.richBlack,
  },
  kiziIconContainer: {
    borderWidth: scaledValue(1),
    width: scaledValue(32),
    height: scaledValue(32),
    borderRadius: scaledValue(16),
    borderColor: colors.primaryBlue,
    right: scaledValue(4),
  },
  kiziIcon: {
    width: scaledValue(32),
    height: scaledValue(32),
    borderRadius: scaledValue(16),
    borderWidth: scaledValue(0.75),
    borderColor: colors.primaryBlue,
    right: scaledValue(4),
  },
  recordFrame: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#fff',
  },
  tabButton: {
    width: Dimensions.get('window').width / 2 - scaledValue(24.5),
  },
  container: {
    position: 'relative',
    borderRadius: scaledValue(1.6),
    overflow: 'hidden',
    marginTop: scaledValue(12),
  },
  petButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaledValue(4),
  },
  catImage: {
    width: scaledValue(39),
    height: scaledValue(39),
    borderRadius: scaledValue(20),
    borderWidth: 1,
    borderColor: colors.primaryBlue,
  },
  arrowImage: {
    width: scaledValue(16),
    height: scaledValue(16),
  },
});
